// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDOpeLAww_RVYm7T-SIZFhsbLmANkeCPE',
    appId: '1:181885205222:web:f520aa231980348172d927',
    messagingSenderId: '181885205222',
    projectId: 'shop-ease-d8eb1',
    authDomain: 'shop-ease-d8eb1.firebaseapp.com',
    storageBucket: 'shop-ease-d8eb1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACV8PRo5Zo1Kpflt8Cysl2GNJQzmQrpGw',
    appId: '1:181885205222:android:f47e89c908b14a4e72d927',
    messagingSenderId: '181885205222',
    projectId: 'shop-ease-d8eb1',
    storageBucket: 'shop-ease-d8eb1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAK0Qj0c8FTa2KpVVR-OYj0a0ciABIqUyc',
    appId: '1:181885205222:ios:e1d668cd454448e972d927',
    messagingSenderId: '181885205222',
    projectId: 'shop-ease-d8eb1',
    storageBucket: 'shop-ease-d8eb1.firebasestorage.app',
    iosBundleId: 'com.example.shopease',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAK0Qj0c8FTa2KpVVR-OYj0a0ciABIqUyc',
    appId: '1:181885205222:ios:e1d668cd454448e972d927',
    messagingSenderId: '181885205222',
    projectId: 'shop-ease-d8eb1',
    storageBucket: 'shop-ease-d8eb1.firebasestorage.app',
    iosBundleId: 'com.example.shopease',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDOpeLAww_RVYm7T-SIZFhsbLmANkeCPE',
    appId: '1:181885205222:web:c33badd362c7741672d927',
    messagingSenderId: '181885205222',
    projectId: 'shop-ease-d8eb1',
    authDomain: 'shop-ease-d8eb1.firebaseapp.com',
    storageBucket: 'shop-ease-d8eb1.firebasestorage.app',
  );
}
